[tool.commitizen]
name = "cz_conventional_commits"
version = "0.10.0"
tag_format = "$version"
version_files = [
    "Cargo.lock:version",
    "Cargo.toml:version",
    "install.sh"
]
bump_message = "chore(release): version $current_version → $new_version"
update_changelog_on_bump = true
