[package]
name = "kdbx"
version = "0.0.1"
authors = ["Danil Akhtarov <daxartio@gmail.com>"]
edition = "2021"
description = "KeePass CLI"
documentation = "https://github.com/daxartio/kdbx"
homepage = "https://github.com/daxartio/kdbx"
repository = "https://github.com/daxartio/kdbx"
readme = "README.md"
keywords = ["keepass", "kdbx4", "password", "kdbx"]
categories = ["command-line-utilities"]
license = "MIT"

[features]
default = ["clipboard"]

[dependencies]
atty = "0.2"
clipboard = { version = "0.5.0", optional = true }
ctrlc = { version = "3.0", features = ["termination"] }
docopt = "1"
env_logger = "0.10"
kdbx4 = "0.5"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_warn"] }
once_cell = "1.8"
serde = "1.0"
serde_derive = "1.0"
skim = "0.10"
libc = "0.2"
keepass = { version = "0.6.1", features = ["save_kdbx4"]}

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "2.4"
