[package]
name = "kdbx"
version = "0.2.0"
authors = ["Danil Akhtarov <daxartio@gmail.com>"]
edition = "2021"
description = "KeePass CLI"
documentation = "https://github.com/daxartio/kdbx"
homepage = "https://github.com/daxartio/kdbx"
repository = "https://github.com/daxartio/kdbx"
readme = "README.md"
keywords = ["keepass", "kdbx4", "password", "kdbx"]
categories = ["command-line-utilities"]
license = "MIT"

[features]
default = ["clipboard"]
clipboard = ["dep:arboard"]

[dependencies]
arboard = { version = "3.2.1", default-features = false, optional = true }
atty = "0.2"
ctrlc = { version = "3.4", features = ["termination"] }
docopt = "1"
env_logger = "0.10"
kdbx4 = "0.5"
keepass = { version = "0.6.1", features = ["save_kdbx4"]}
libc = "0.2"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_warn"] }
once_cell = "1.18"
serde = "1"
serde_derive = "1"
skim = "0.10"

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "2.9"
