[package]
name = "kdbx"
version = "0.6.0"
authors = ["Danil Akhtarov <daxartio@gmail.com>"]
edition = "2021"
description = "KeePass CLI"
documentation = "https://github.com/daxartio/kdbx"
homepage = "https://github.com/daxartio/kdbx"
repository = "https://github.com/daxartio/kdbx"
readme = "README.md"
keywords = ["keepass", "kdbx4", "password", "kdbx"]
categories = ["command-line-utilities"]
license = "MIT"

[features]
default = ["clipboard"]
clipboard = ["dep:arboard"]

[dependencies]
arboard = { version = "3.2.1", default-features = false, optional = true }
atty = "0.2"
clap = { version = "4.4.8", features = ["derive", "env"] }
ctrlc = { version = "3.4", features = ["termination"] }
env_logger = "0.10"
keepass = { version = "0.6.8", features = ["save_kdbx4", "totp"]}
libc = "0.2"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_warn"] }
once_cell = "1.18"

[target.'cfg(not(windows))'.dependencies]
skim = "0.10"

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.4"
rstest = "0.18.2"

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "2.9"
