[package]
name = "kdbx"
version = "0.8.0"
authors = ["Danil Akhtarov <daxartio@gmail.com>"]
edition = "2021"
description = "KeePass CLI"
documentation = "https://github.com/daxartio/kdbx"
homepage = "https://github.com/daxartio/kdbx"
repository = "https://github.com/daxartio/kdbx"
readme = "README.md"
keywords = ["keepass", "kdbx4", "password", "kdbx"]
categories = ["command-line-utilities"]
license = "MIT"

[features]
default = ["clipboard"]
clipboard = ["dep:arboard"]

[dependencies]
arboard = { version = "3.3.1", default-features = false, optional = true }
atty = "0.2"
clap = { version = "4.5.1", features = ["derive", "env"] }
clap_complete = "4.5.1"
ctrlc = { version = "3.4", features = ["termination"] }
env_logger = "0.11"
human-panic = "1.2.3"
keepass = { version = "0.7.6", features = ["save_kdbx4", "totp"]}
libc = "0.2"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_warn"] }
once_cell = "1.19"

[target.'cfg(not(windows))'.dependencies]
skim = "0.10"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
rstest = "0.18.2"

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "2.9"
